language: python

matrix:
    include:
        - python: 3.8
        - python: 3.7
        - python: 3.6
          dist: bionic
        - python: 3.5
          dist: xenial 
        - python: 2.7
          dist: bionic
        - python: pypy3
        - python: nightly

before_install:
  - pip install --upgrade pip
  - pip install poetry
  - pip install codecov

install:
  - poetry install --no-root

script:
  - pip install .
  - python -m pytest tests
  - python -m flake8 src

after_success:
  - python -m codecov
